node {
    environment {
        registry = "pcschool/sop"
        registryCredential = 'dockerhub'
        dockerImage = ''
    }
    withMaven(maven:'maven') {

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('jenkins-service') {
                def app = docker.build "localhost:5000/jenkins-service:${env.version}"
                app.push()
            }
        }

        stage ('Test') {
            docker.image("localhost:5000/jenkins-service:${env.version}").run('-p 2222:2222 -h account --name account --link discovery')
        }

        stage ('Deployment') {
            steps {
                    sh 'docker login -u pcschool -p P@ssw0rd'
                    docker.withRegistry( '', registryCredential) {
                        docker.image.push()
                }
            }
            //build job: 'jenkins', wait: false
        }     

    }

}